caches: 
  - name: "requirements"
    cache_key: 
      - "requirements-v1"
      - agent: "os"
    target_paths: 
      - "/Users/andrea_ovalle/Development/bk_playground/ao-bk-playground/requirements-e2e.txt"