env: 
  BUILDKITE_AGENT_CACHE_STORE_URL: "s3://s3-cache-andrea/buildkite?region=us-east-1"
  QUEUE: "cache"

steps: 
  - key: "cache"
    label: ":toolbox: Restore and Save Cache"
    agents: 
      queue: "$${QUEUE}"
    command: |

      set -euo pipefail 
      echo ":runner: Running cache restore and save steps ... "

      buildkite-agent cache restore --name requirements 
      echo " :white_check_mark: Cache restore completed."

      buildkite-agent cache save --name requirements 
      echo " :white_check_mark: Cache save completed."