env: 
  BUILDKITE_AGENT_CACHE_STORE_URL: "s3://s3-cache-andrea/buildkite?region=us-east-1"

steps: 
  - key: "cache"
    label: ":cache: Restore and Save Cache"
    command: |

      set -euo pipefail 
      echo "Running cache restore and save steps ... "

      buildkite-agent cache restore --name requirements 
      echo "Cache restore completed."
      buildkite-agent cache save --name requirements 
      echo "Cache save completed."