steps:
  - key: "docker"
    label: ":docker: Build, Login & Push app/server"
    agents:
      queue: "webhook-acquire"
    commands:
      - echo "Building Docker image"
      - docker build --tag packages.buildkite.com/spacecamp/ao-bk-playground/app:latest ./app # this is the path to the Dockerfile for the app image in the repo
      - docker build --tag packages.buildkite.com/spacecamp/ao-bk-playground/server:latest ./server # this is the path to the Dockerfile for the server image in the repo

      - echo "Logging into bk package registry using OIDC"
      - buildkite-agent oidc request-token --audience "https://packages.buildkite.com/spacecamp/ao-bk-playground" --lifetime 300 | docker login packages.buildkite.com/spacecamp/ao-bk-playground --username buildkite --password-stdin
      
      - echo "Pushing Docker image to bk registry"
      - docker push packages.buildkite.com/spacecamp/ao-bk-playground/app:latest
      - docker push packages.buildkite.com/spacecamp/ao-bk-playground/server:latest 



  # - label: ":docker: Check Docker"
  #   command: |
  #     command -v docker
  #     docker version
  #     docker compose version

  # - label: ":docker: Validate Compose"
  #   command: "docker compose config"
  
  # - label: ":docker: Build images"
  #   key: "build-images"
  #   command: "docker compose build"

  # - label: ":docker: Smoke test"
  #   key: "compose-smoke-test"
  #   depends_on: "build-images"
  #   concurrency: 1 ## limits on how many builds can run concurrently for this step
  #   concurrency_group: "nasa-image-app" ## the limits are tied to this group name, so all builds with the same group name will be limited
  #   secrets:
  #     API_TOKEN: NASA_API_TOKEN
  #   command: |
  #     set -euo pipefail


  #     docker compose up --build --detach
  
  # - label: "UI/API test"      
  #   key: "ui-test"
  #   depends_on: "compose-smoke-test"
  #   command: |
  #     curl --fail http://localhost:8080
  #     curl --fail http://localhost:3000/api/nasaimage

